### ISSUE TITLE
docker-compose container fails to init, complaining about iptables

### ISSUE THREAD

**Issue by DeaeLunae** [kasmtech/kasm-workspaces-dind#1]
Small changes to compose, mapping 4433 to 443, otherwise the same as in readme.md, also changed to develop, but did so as 1.11.0 was experiencing the same issue.

docker-compose.yml:
```yaml
version: "2.1"
services:
  kasm:
    image: kasmweb/workspaces:develop
    privileged: true
    container_name: kasm
    environment:
      - KASM_PORT=443 #optional
      - DOCKER_HUB_USERNAME= #optional
      - DOCKER_HUB_PASSWORD= #optional
    volumes:
      - /kasm/local/storage:/opt
    ports:
      - 4433:443
      - 3000:3000
    restart: unless-stopped
```

Log:
```
kasm  | [cont-init.d] 01-motd: exited 0.
kasm  | [cont-init.d] 02-setup: executing... 
kasm  | [cont-init.d] 02-setup: exited 0.
kasm  | [cont-init.d] done.
kasm  | [services.d] starting services
kasm  | [services.d] done.
kasm  | modprobe: can't change directory to '/lib/modules': No such file or directory
kasm  | [WARN  tini (214)] Tini is not running as PID 1 and isn't registered as a child subreaper.
kasm  | Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
kasm  | To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
kasm  | time="2022-08-06T03:58:40Z" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
kasm  | time="2022-08-06T03:58:40.663013957Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
kasm  | failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create FILTER chain DOCKER: iptables failed: iptables -t filter -N DOCKER: iptables v1.8.8 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
kasm  | Perhaps iptables or your kernel needs to be upgraded.
kasm  |  (exit status 3)
[last 9 lines repeat until terminated]
```

Invoking iptables in the container:
```
# docker compose exec -it kasm bash
bash-5.1# iptables -L
iptables v1.8.8 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
bash-5.1# 
```

Any idea why this might be happening?
