### ISSUE TITLE
Unable to Connect to Web Interface via nonstandard port

### ISSUE THREAD

**Issue by SxthGear** [kasmtech/kasm-workspaces-dind#2]
Docker-Compose.yaml

```
version: "2.1"
services:
  kasm:
    image: kasmweb/workspaces:1.11.0
    privileged: true
    container_name: kasm
    environment:
      - KASM_PORT=443
    volumes:
      - /docker/containers/kasm/:/opt
    ports:
      - 4443:443
      - 3099:3000
    restart: unless-stopped
```

Able to log into the install interface on port 3099, however connecting to the host on https://hostname:4443 yields a connection refused from the browser. Testing with setting the `KASM_PORT` env variable set to both 443 or 4443 with same result. No errors noted in the log for the kasm container.
