### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by webysther** [kasmtech/kasm-workspaces-dind#3]
Any chance to provide a alternative install with docker compose? Will be nice have a official model to plug more agents in another machines.

**Comment by webysther** [comment]
Inside the build install on [terraform](https://github.com/kasmtech/terraform/tree/develop/aws/standard):

```
kasm_build https://kasm-static-content.s3.amazonaws.com/kasm_release_1.12.0.d4fd8a.tar.gz

./kasm_release/docker/*.yaml
```

Have all compose file (all):

```
version: '3'
services:
  db:
    container_name: kasm_db
    image: postgres:12-alpine
    restart: always
    healthcheck:
      test: "pg_isready --username=kasmapp && cat /proc/1/cmdline | grep -q '^postgres'"
      timeout: 5s
      retries: 20
    networks:
      - kasm_default_network
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: kasmapp
      POSTGRES_DB: kasm
    volumes:
      - /opt/kasm/1.12.0/conf/database/data.sql:/docker-entrypoint-initdb.d/data.sql
      - /opt/kasm/1.12.0/conf/database/pg_hba.conf:/var/lib/postgresql/conf/pg_hba.conf
      - /opt/kasm/1.12.0/conf/database/postgresql.conf:/var/lib/postgresql/conf/postgresql.conf
      - /opt/kasm/1.12.0/conf/database/:/tmp/
      - /opt/kasm/1.12.0/certs/db_server.crt:/etc/ssl/certs/db_server.crt
      - /opt/kasm/1.12.0/certs/db_server.key:/etc/ssl/certs/db_server.key
      - /opt/kasm/1.12.0/log/postgres/:/var/log/postgres/
      - kasm_db_1.12.0:/var/lib/postgresql/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    command: postgres -c ssl=on -c ssl_cert_file=/etc/ssl/certs/db_server.crt -c ssl_key_file=/etc/ssl/certs/db_server.key -c config_file=/var/lib/postgresql/conf/postgresql.conf -c hba_file=/var/lib/postgresql/conf/pg_hba.conf
  kasm_redis:
    container_name: kasm_redis
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    user: "${KASM_UID?}:${KASM_GID?}"
    image: redis:5-alpine
    restart: always
    networks:
      - kasm_default_network
    environment:
      REDIS_PASSWORD: changeme
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_api:
    container_name: kasm_api
    user: "${KASM_UID?}:${KASM_GID?}"
    image: "kasmweb/api:1.12.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.12.0:/opt/kasm/current
      - /opt/kasm/1.12.0/tmp/api:/tmp
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_manager:
    container_name: kasm_manager
    user: "${KASM_UID?}:${KASM_GID?}"
    image: "kasmweb/manager:1.12.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.12.0:/opt/kasm/current
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_agent:
    container_name: kasm_agent
    user: root
    image: "kasmweb/agent:1.12.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.12.0:/opt/kasm/current
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /opt/kasm/1.12.0/conf/nginx:/etc/nginx/conf.d
    depends_on:
      - kasm_manager
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_share:
    container_name: kasm_share
    user: root
    image: "kasmweb/share:1.12.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.12.0:/opt/kasm/current
    restart: always
    depends_on:
      - db
      - kasm_redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_guac:
    container_name: kasm_guac
    user: "${KASM_UID?}:${KASM_GID?}"
    image: "kasmweb/kasm-guac:1.12.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.12.0:/opt/kasm/current
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  proxy:
    container_name: kasm_proxy
    image: "kasmweb/nginx:latest"
    ports:
      - "443:443"
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.12.0/conf/nginx:/etc/nginx/conf.d:ro
      - /opt/kasm/1.12.0/certs/kasm_nginx.key:/etc/ssl/private/kasm_nginx.key
      - /opt/kasm/1.12.0/certs/kasm_nginx.crt:/etc/ssl/certs/kasm_nginx.crt
      - /opt/kasm/1.12.0/www:/srv/www:ro
      - /opt/kasm/1.12.0/log/nginx:/var/log/external/nginx/
      - /opt/kasm/1.12.0/log/logrotate:/var/log/external/logrotate/
    depends_on:
      - kasm_manager
      - kasm_api
      - kasm_agent
      - kasm_share
      - kasm_guac
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
volumes:
  kasm_db_1.12.0:
    external: true

networks:
  kasm_default_network:
    external: true
```
